# Generated by Django 4.2.4 on 2023-08-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Machine_Id'),
        ),
    ]
