# Generated by Django 4.2.4 on 2023-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_alter_laptop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
